"""create breed column 

Revision ID: 894d3d910f09
Revises: 
Create Date: 2018-11-13 06:51:41.902892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894d3d910f09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
